// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: error_log.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countErrorLogsByDateRange = `-- name: CountErrorLogsByDateRange :one
SELECT COUNT(*) FROM error_logs
WHERE created_at >= $1 AND created_at < $2
`

type CountErrorLogsByDateRangeParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

func (q *Queries) CountErrorLogsByDateRange(ctx context.Context, arg CountErrorLogsByDateRangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countErrorLogsByDateRange, arg.CreatedAt, arg.CreatedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countErrorLogsByType = `-- name: CountErrorLogsByType :one
SELECT COUNT(*) FROM error_logs
WHERE error_type = $1
`

func (q *Queries) CountErrorLogsByType(ctx context.Context, errorType string) (int64, error) {
	row := q.db.QueryRow(ctx, countErrorLogsByType, errorType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createErrorLog = `-- name: CreateErrorLog :one
INSERT INTO error_logs (
    user_id,
    request_id,
    error_type,
    error_message,
    stack_trace,
    request_path,
    request_method,
    ip_address,
    user_agent,
    metadata,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, user_id, request_id, error_type, error_message, stack_trace, request_path, request_method, ip_address, user_agent, metadata, created_at
`

type CreateErrorLogParams struct {
	UserID        pgtype.UUID        `json:"user_id"`
	RequestID     pgtype.Text        `json:"request_id"`
	ErrorType     string             `json:"error_type"`
	ErrorMessage  string             `json:"error_message"`
	StackTrace    pgtype.Text        `json:"stack_trace"`
	RequestPath   pgtype.Text        `json:"request_path"`
	RequestMethod pgtype.Text        `json:"request_method"`
	IpAddress     pgtype.Text        `json:"ip_address"`
	UserAgent     pgtype.Text        `json:"user_agent"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateErrorLog(ctx context.Context, arg CreateErrorLogParams) (ErrorLog, error) {
	row := q.db.QueryRow(ctx, createErrorLog,
		arg.UserID,
		arg.RequestID,
		arg.ErrorType,
		arg.ErrorMessage,
		arg.StackTrace,
		arg.RequestPath,
		arg.RequestMethod,
		arg.IpAddress,
		arg.UserAgent,
		arg.Metadata,
		arg.CreatedAt,
	)
	var i ErrorLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestID,
		&i.ErrorType,
		&i.ErrorMessage,
		&i.StackTrace,
		&i.RequestPath,
		&i.RequestMethod,
		&i.IpAddress,
		&i.UserAgent,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getErrorLogByID = `-- name: GetErrorLogByID :one
SELECT id, user_id, request_id, error_type, error_message, stack_trace, request_path, request_method, ip_address, user_agent, metadata, created_at FROM error_logs
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetErrorLogByID(ctx context.Context, id pgtype.UUID) (ErrorLog, error) {
	row := q.db.QueryRow(ctx, getErrorLogByID, id)
	var i ErrorLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestID,
		&i.ErrorType,
		&i.ErrorMessage,
		&i.StackTrace,
		&i.RequestPath,
		&i.RequestMethod,
		&i.IpAddress,
		&i.UserAgent,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listErrorLogsByDateRange = `-- name: ListErrorLogsByDateRange :many
SELECT id, user_id, request_id, error_type, error_message, stack_trace, request_path, request_method, ip_address, user_agent, metadata, created_at FROM error_logs
WHERE created_at >= $1 AND created_at < $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListErrorLogsByDateRangeParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
	Limit       int32              `json:"limit"`
	Offset      int32              `json:"offset"`
}

func (q *Queries) ListErrorLogsByDateRange(ctx context.Context, arg ListErrorLogsByDateRangeParams) ([]ErrorLog, error) {
	rows, err := q.db.Query(ctx, listErrorLogsByDateRange,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErrorLog{}
	for rows.Next() {
		var i ErrorLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RequestID,
			&i.ErrorType,
			&i.ErrorMessage,
			&i.StackTrace,
			&i.RequestPath,
			&i.RequestMethod,
			&i.IpAddress,
			&i.UserAgent,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listErrorLogsByPath = `-- name: ListErrorLogsByPath :many
SELECT id, user_id, request_id, error_type, error_message, stack_trace, request_path, request_method, ip_address, user_agent, metadata, created_at FROM error_logs
WHERE request_path = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListErrorLogsByPathParams struct {
	RequestPath pgtype.Text `json:"request_path"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

func (q *Queries) ListErrorLogsByPath(ctx context.Context, arg ListErrorLogsByPathParams) ([]ErrorLog, error) {
	rows, err := q.db.Query(ctx, listErrorLogsByPath, arg.RequestPath, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErrorLog{}
	for rows.Next() {
		var i ErrorLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RequestID,
			&i.ErrorType,
			&i.ErrorMessage,
			&i.StackTrace,
			&i.RequestPath,
			&i.RequestMethod,
			&i.IpAddress,
			&i.UserAgent,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listErrorLogsByRequestID = `-- name: ListErrorLogsByRequestID :many
SELECT id, user_id, request_id, error_type, error_message, stack_trace, request_path, request_method, ip_address, user_agent, metadata, created_at FROM error_logs
WHERE request_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListErrorLogsByRequestID(ctx context.Context, requestID pgtype.Text) ([]ErrorLog, error) {
	rows, err := q.db.Query(ctx, listErrorLogsByRequestID, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErrorLog{}
	for rows.Next() {
		var i ErrorLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RequestID,
			&i.ErrorType,
			&i.ErrorMessage,
			&i.StackTrace,
			&i.RequestPath,
			&i.RequestMethod,
			&i.IpAddress,
			&i.UserAgent,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listErrorLogsByType = `-- name: ListErrorLogsByType :many
SELECT id, user_id, request_id, error_type, error_message, stack_trace, request_path, request_method, ip_address, user_agent, metadata, created_at FROM error_logs
WHERE error_type = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListErrorLogsByTypeParams struct {
	ErrorType string `json:"error_type"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListErrorLogsByType(ctx context.Context, arg ListErrorLogsByTypeParams) ([]ErrorLog, error) {
	rows, err := q.db.Query(ctx, listErrorLogsByType, arg.ErrorType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErrorLog{}
	for rows.Next() {
		var i ErrorLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RequestID,
			&i.ErrorType,
			&i.ErrorMessage,
			&i.StackTrace,
			&i.RequestPath,
			&i.RequestMethod,
			&i.IpAddress,
			&i.UserAgent,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listErrorLogsByUser = `-- name: ListErrorLogsByUser :many
SELECT id, user_id, request_id, error_type, error_message, stack_trace, request_path, request_method, ip_address, user_agent, metadata, created_at FROM error_logs
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListErrorLogsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListErrorLogsByUser(ctx context.Context, arg ListErrorLogsByUserParams) ([]ErrorLog, error) {
	rows, err := q.db.Query(ctx, listErrorLogsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErrorLog{}
	for rows.Next() {
		var i ErrorLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RequestID,
			&i.ErrorType,
			&i.ErrorMessage,
			&i.StackTrace,
			&i.RequestPath,
			&i.RequestMethod,
			&i.IpAddress,
			&i.UserAgent,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentErrors = `-- name: ListRecentErrors :many
SELECT id, user_id, request_id, error_type, error_message, stack_trace, request_path, request_method, ip_address, user_agent, metadata, created_at FROM error_logs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListRecentErrorsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRecentErrors(ctx context.Context, arg ListRecentErrorsParams) ([]ErrorLog, error) {
	rows, err := q.db.Query(ctx, listRecentErrors, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErrorLog{}
	for rows.Next() {
		var i ErrorLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RequestID,
			&i.ErrorType,
			&i.ErrorMessage,
			&i.StackTrace,
			&i.RequestPath,
			&i.RequestMethod,
			&i.IpAddress,
			&i.UserAgent,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
