// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditAction string

const (
	AuditActionCREATE AuditAction = "CREATE"
	AuditActionUPDATE AuditAction = "UPDATE"
	AuditActionDELETE AuditAction = "DELETE"
)

func (e *AuditAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditAction(s)
	case string:
		*e = AuditAction(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditAction: %T", src)
	}
	return nil
}

type NullAuditAction struct {
	AuditAction AuditAction `json:"audit_action"`
	Valid       bool        `json:"valid"` // Valid is true if AuditAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditAction) Scan(value interface{}) error {
	if value == nil {
		ns.AuditAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditAction), nil
}

type Admin struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	FirstName    pgtype.Text        `json:"first_name"`
	LastName     pgtype.Text        `json:"last_name"`
	Role         string             `json:"role"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type AuditLog struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Action     AuditAction        `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	OldData    []byte             `json:"old_data"`
	NewData    []byte             `json:"new_data"`
	RequestID  pgtype.Text        `json:"request_id"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AuditLogs202511 struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Action     AuditAction        `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	OldData    []byte             `json:"old_data"`
	NewData    []byte             `json:"new_data"`
	RequestID  pgtype.Text        `json:"request_id"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AuditLogs202512 struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Action     AuditAction        `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	OldData    []byte             `json:"old_data"`
	NewData    []byte             `json:"new_data"`
	RequestID  pgtype.Text        `json:"request_id"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AuditLogs202601 struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Action     AuditAction        `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	OldData    []byte             `json:"old_data"`
	NewData    []byte             `json:"new_data"`
	RequestID  pgtype.Text        `json:"request_id"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AuditLogs202602 struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Action     AuditAction        `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	OldData    []byte             `json:"old_data"`
	NewData    []byte             `json:"new_data"`
	RequestID  pgtype.Text        `json:"request_id"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AuditLogsDefault struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Action     AuditAction        `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	OldData    []byte             `json:"old_data"`
	NewData    []byte             `json:"new_data"`
	RequestID  pgtype.Text        `json:"request_id"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ErrorLog struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	RequestID     pgtype.Text        `json:"request_id"`
	ErrorType     string             `json:"error_type"`
	ErrorMessage  string             `json:"error_message"`
	StackTrace    pgtype.Text        `json:"stack_trace"`
	RequestPath   pgtype.Text        `json:"request_path"`
	RequestMethod pgtype.Text        `json:"request_method"`
	IpAddress     pgtype.Text        `json:"ip_address"`
	UserAgent     pgtype.Text        `json:"user_agent"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ErrorLogs202511 struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	RequestID     pgtype.Text        `json:"request_id"`
	ErrorType     string             `json:"error_type"`
	ErrorMessage  string             `json:"error_message"`
	StackTrace    pgtype.Text        `json:"stack_trace"`
	RequestPath   pgtype.Text        `json:"request_path"`
	RequestMethod pgtype.Text        `json:"request_method"`
	IpAddress     pgtype.Text        `json:"ip_address"`
	UserAgent     pgtype.Text        `json:"user_agent"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ErrorLogs202512 struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	RequestID     pgtype.Text        `json:"request_id"`
	ErrorType     string             `json:"error_type"`
	ErrorMessage  string             `json:"error_message"`
	StackTrace    pgtype.Text        `json:"stack_trace"`
	RequestPath   pgtype.Text        `json:"request_path"`
	RequestMethod pgtype.Text        `json:"request_method"`
	IpAddress     pgtype.Text        `json:"ip_address"`
	UserAgent     pgtype.Text        `json:"user_agent"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ErrorLogs202601 struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	RequestID     pgtype.Text        `json:"request_id"`
	ErrorType     string             `json:"error_type"`
	ErrorMessage  string             `json:"error_message"`
	StackTrace    pgtype.Text        `json:"stack_trace"`
	RequestPath   pgtype.Text        `json:"request_path"`
	RequestMethod pgtype.Text        `json:"request_method"`
	IpAddress     pgtype.Text        `json:"ip_address"`
	UserAgent     pgtype.Text        `json:"user_agent"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ErrorLogs202602 struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	RequestID     pgtype.Text        `json:"request_id"`
	ErrorType     string             `json:"error_type"`
	ErrorMessage  string             `json:"error_message"`
	StackTrace    pgtype.Text        `json:"stack_trace"`
	RequestPath   pgtype.Text        `json:"request_path"`
	RequestMethod pgtype.Text        `json:"request_method"`
	IpAddress     pgtype.Text        `json:"ip_address"`
	UserAgent     pgtype.Text        `json:"user_agent"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ErrorLogsDefault struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	RequestID     pgtype.Text        `json:"request_id"`
	ErrorType     string             `json:"error_type"`
	ErrorMessage  string             `json:"error_message"`
	StackTrace    pgtype.Text        `json:"stack_trace"`
	RequestPath   pgtype.Text        `json:"request_path"`
	RequestMethod pgtype.Text        `json:"request_method"`
	IpAddress     pgtype.Text        `json:"ip_address"`
	UserAgent     pgtype.Text        `json:"user_agent"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type MenuItem struct {
	ID           pgtype.UUID        `json:"id"`
	ParentID     pgtype.UUID        `json:"parent_id"`
	Code         string             `json:"code"`
	Label        string             `json:"label"`
	Icon         pgtype.Text        `json:"icon"`
	Path         pgtype.Text        `json:"path"`
	PermissionID pgtype.UUID        `json:"permission_id"`
	OrderIndex   int32              `json:"order_index"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Order struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	OrderNumber string             `json:"order_number"`
	Status      string             `json:"status"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	Notes       pgtype.Text        `json:"notes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Orders2025 struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	OrderNumber string             `json:"order_number"`
	Status      string             `json:"status"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	Notes       pgtype.Text        `json:"notes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Orders2026 struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	OrderNumber string             `json:"order_number"`
	Status      string             `json:"status"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	Notes       pgtype.Text        `json:"notes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type OrdersDefault struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	OrderNumber string             `json:"order_number"`
	Status      string             `json:"status"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	Notes       pgtype.Text        `json:"notes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Permission struct {
	ID          pgtype.UUID        `json:"id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Category    string             `json:"category"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RolePermission struct {
	ID           pgtype.UUID        `json:"id"`
	Role         string             `json:"role"`
	PermissionID pgtype.UUID        `json:"permission_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	FirstName    pgtype.Text        `json:"first_name"`
	LastName     pgtype.Text        `json:"last_name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
