// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permission.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignPermissionToRole = `-- name: AssignPermissionToRole :exec
INSERT INTO role_permissions (role, permission_id)
VALUES ($1, $2)
ON CONFLICT (role, permission_id) DO NOTHING
`

type AssignPermissionToRoleParams struct {
	Role         string      `json:"role"`
	PermissionID pgtype.UUID `json:"permission_id"`
}

func (q *Queries) AssignPermissionToRole(ctx context.Context, arg AssignPermissionToRoleParams) error {
	_, err := q.db.Exec(ctx, assignPermissionToRole, arg.Role, arg.PermissionID)
	return err
}

const createPermission = `-- name: CreatePermission :one
INSERT INTO permissions (code, name, description, category)
VALUES ($1, $2, $3, $4)
RETURNING id, code, name, description, category, is_active, created_at, updated_at
`

type CreatePermissionParams struct {
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Category    string      `json:"category"`
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, createPermission,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Category,
	)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePermission = `-- name: DeletePermission :exec
DELETE FROM permissions WHERE id = $1
`

func (q *Queries) DeletePermission(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePermission, id)
	return err
}

const getAllPermissions = `-- name: GetAllPermissions :many
SELECT id, code, name, description, category, is_active, created_at, updated_at FROM permissions
WHERE is_active = true
ORDER BY category, code
`

func (q *Queries) GetAllPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getAllPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermissionByCode = `-- name: GetPermissionByCode :one
SELECT id, code, name, description, category, is_active, created_at, updated_at FROM permissions
WHERE code = $1 AND is_active = true
`

func (q *Queries) GetPermissionByCode(ctx context.Context, code string) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionByCode, code)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPermissionsByRole = `-- name: GetPermissionsByRole :many
SELECT p.id, p.code, p.name, p.description, p.category, p.is_active, p.created_at, p.updated_at
FROM permissions p
INNER JOIN role_permissions rp ON rp.permission_id = p.id
WHERE rp.role = $1 AND p.is_active = true
`

func (q *Queries) GetPermissionsByRole(ctx context.Context, role string) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getPermissionsByRole, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRolePermissionCodes = `-- name: GetRolePermissionCodes :many
SELECT p.code
FROM permissions p
INNER JOIN role_permissions rp ON rp.permission_id = p.id
WHERE rp.role = $1 AND p.is_active = true
`

func (q *Queries) GetRolePermissionCodes(ctx context.Context, role string) ([]string, error) {
	rows, err := q.db.Query(ctx, getRolePermissionCodes, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokePermissionFromRole = `-- name: RevokePermissionFromRole :exec
DELETE FROM role_permissions
WHERE role = $1 AND permission_id = $2
`

type RevokePermissionFromRoleParams struct {
	Role         string      `json:"role"`
	PermissionID pgtype.UUID `json:"permission_id"`
}

func (q *Queries) RevokePermissionFromRole(ctx context.Context, arg RevokePermissionFromRoleParams) error {
	_, err := q.db.Exec(ctx, revokePermissionFromRole, arg.Role, arg.PermissionID)
	return err
}

const updatePermission = `-- name: UpdatePermission :one
UPDATE permissions
SET name = COALESCE($2, name),
    description = COALESCE($3, description),
    category = COALESCE($4, category),
    is_active = COALESCE($5, is_active)
WHERE id = $1
RETURNING id, code, name, description, category, is_active, created_at, updated_at
`

type UpdatePermissionParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	Category    pgtype.Text `json:"category"`
	IsActive    pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpdatePermission(ctx context.Context, arg UpdatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, updatePermission,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.IsActive,
	)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
