// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AssignPermissionToRole(ctx context.Context, arg AssignPermissionToRoleParams) error
	ClearDefaultAddress(ctx context.Context, id pgtype.UUID) (User, error)
	CountAddresses(ctx context.Context) (int64, error)
	CountAddressesByUserID(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountAuditLogsByEntity(ctx context.Context, arg CountAuditLogsByEntityParams) (int64, error)
	CountAuditLogsByUser(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountErrorLogsByDateRange(ctx context.Context, arg CountErrorLogsByDateRangeParams) (int64, error)
	CountErrorLogsByType(ctx context.Context, errorType string) (int64, error)
	CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error)
	CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateErrorLog(ctx context.Context, arg CreateErrorLogParams) (ErrorLog, error)
	CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (MenuItem, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAddress(ctx context.Context, id pgtype.UUID) error
	DeleteAddressForUser(ctx context.Context, arg DeleteAddressForUserParams) error
	DeleteAddressesByUserID(ctx context.Context, userID pgtype.UUID) error
	DeleteAdmin(ctx context.Context, id pgtype.UUID) error
	DeleteMenuItem(ctx context.Context, id pgtype.UUID) error
	DeleteOrder(ctx context.Context, id pgtype.UUID) error
	DeletePermission(ctx context.Context, id pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetAddressByID(ctx context.Context, id pgtype.UUID) (Address, error)
	GetAddressByIDAndUserID(ctx context.Context, arg GetAddressByIDAndUserIDParams) (Address, error)
	GetAddressesByUserID(ctx context.Context, userID pgtype.UUID) ([]Address, error)
	GetAdminByEmail(ctx context.Context, email string) (Admin, error)
	GetAdminByID(ctx context.Context, id pgtype.UUID) (Admin, error)
	GetAdminByUsername(ctx context.Context, username string) (Admin, error)
	GetAllMenuItems(ctx context.Context) ([]MenuItem, error)
	GetAllPermissions(ctx context.Context) ([]Permission, error)
	GetAuditLogByID(ctx context.Context, id pgtype.UUID) (AuditLog, error)
	GetChildMenuItems(ctx context.Context, parentID pgtype.UUID) ([]MenuItem, error)
	GetErrorLogByID(ctx context.Context, id pgtype.UUID) (ErrorLog, error)
	GetMenuItemByCode(ctx context.Context, code string) (MenuItem, error)
	GetMenuItemByID(ctx context.Context, id pgtype.UUID) (MenuItem, error)
	GetMenuItemsByRole(ctx context.Context, role string) ([]GetMenuItemsByRoleRow, error)
	GetOrderByID(ctx context.Context, id pgtype.UUID) (Order, error)
	GetOrderByOrderNumber(ctx context.Context, orderNumber string) (Order, error)
	GetPermissionByCode(ctx context.Context, code string) (Permission, error)
	GetPermissionsByRole(ctx context.Context, role string) ([]Permission, error)
	GetRolePermissionCodes(ctx context.Context, role string) ([]string, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserWithDefaultAddress(ctx context.Context, id pgtype.UUID) (GetUserWithDefaultAddressRow, error)
	HardDeleteAdmin(ctx context.Context, id pgtype.UUID) error
	ListAdmins(ctx context.Context, arg ListAdminsParams) ([]Admin, error)
	ListAllAddresses(ctx context.Context, arg ListAllAddressesParams) ([]Address, error)
	ListAuditLogsByDateRange(ctx context.Context, arg ListAuditLogsByDateRangeParams) ([]AuditLog, error)
	ListAuditLogsByEntity(ctx context.Context, arg ListAuditLogsByEntityParams) ([]AuditLog, error)
	ListAuditLogsByEntityAndDateRange(ctx context.Context, arg ListAuditLogsByEntityAndDateRangeParams) ([]AuditLog, error)
	ListAuditLogsByEntityType(ctx context.Context, arg ListAuditLogsByEntityTypeParams) ([]AuditLog, error)
	ListAuditLogsByRequestID(ctx context.Context, requestID pgtype.Text) ([]AuditLog, error)
	ListAuditLogsByUser(ctx context.Context, arg ListAuditLogsByUserParams) ([]AuditLog, error)
	ListErrorLogsByDateRange(ctx context.Context, arg ListErrorLogsByDateRangeParams) ([]ErrorLog, error)
	ListErrorLogsByPath(ctx context.Context, arg ListErrorLogsByPathParams) ([]ErrorLog, error)
	ListErrorLogsByRequestID(ctx context.Context, requestID pgtype.Text) ([]ErrorLog, error)
	ListErrorLogsByType(ctx context.Context, arg ListErrorLogsByTypeParams) ([]ErrorLog, error)
	ListErrorLogsByUser(ctx context.Context, arg ListErrorLogsByUserParams) ([]ErrorLog, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error)
	ListOrdersByUserID(ctx context.Context, arg ListOrdersByUserIDParams) ([]Order, error)
	ListRecentErrors(ctx context.Context, arg ListRecentErrorsParams) ([]ErrorLog, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	RevokePermissionFromRole(ctx context.Context, arg RevokePermissionFromRoleParams) error
	SetDefaultAddress(ctx context.Context, arg SetDefaultAddressParams) (User, error)
	SetDefaultAddressForUser(ctx context.Context, arg SetDefaultAddressForUserParams) (User, error)
	UpdateAddress(ctx context.Context, arg UpdateAddressParams) (Address, error)
	UpdateAddressForUser(ctx context.Context, arg UpdateAddressForUserParams) (Address, error)
	UpdateAdmin(ctx context.Context, arg UpdateAdminParams) (Admin, error)
	UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) (MenuItem, error)
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdatePermission(ctx context.Context, arg UpdatePermissionParams) (Permission, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
